export default {
  // ⚠️ NEVER put your actual key here. It is loaded securely from GitHub Secrets.
  YOUTUBE_API_KEY: import.meta.env.VITE_YOUTUBE_API_KEY || '', 
    YOUTUBE_CHANNEL_ID: "UC41xXhw22o6Q2I2pTKB2kOg",
    PLAYLISTS: [
    "PLhErNUuDxs_2F8ayJ_XDrgCbH-CiAqRcd",
    "PLhErNUuDxs_04gGj-HoaSkXNQ1bno89I8", // Fixed ID from your link
    "PLhErNUuDxs_0OFY1a8itinxcWutV7oN78",
    "PLhErNUuDxs_3s5P3kfBg1wZdWJY_PmAfC",
  ],
    CATEGORIES: [
    { id: "all", label: "All", icon: "🌍", keywords: [] },
    { id: "ocean", label: "Ocean", icon: "🌊", keywords: ["ocean", "sea", "marine", "whale", "dolphin", "shark", "coral", "fish", "underwater", "coast", "beach", "oceana"] },
    { id: "wildlife", label: "Wildlife", icon: "🦁", keywords: ["wildlife", "safari", "africa", "kruger", "predator", "hunt", "jungle", "savana", "endangered", "conservation"] },
    { id: "animals", label: "Animals", icon: "🐾", keywords: ["animal", "dog", "cat", "bird", "elephant", "lion", "tiger", "bear", "monkey", "snake", "insect", "species"] },
    { id: "nature", label: "Nature", icon: "🌿", keywords: ["nature", "forest", "tree", "plant", "flower", "ecosystem", "biodiversity", "habitat", "rainforest"] },
    { id: "science", label: "Science", icon: "🔬", keywords: ["science", "research", "study", "discovery", "species", "biology", "evolution", "fossil"] },
  ],
    RSS_FEEDS: [
    { url: "https://www.nationalgeographic.com/animals/rss", name: "National Geographic" },
    { url: "https://www.worldwildlife.org/feeds/news", name: "World Wildlife Fund" },
    { url: "https://africageographic.com/feed/", name: "Africa Geographic" },
    { url: "https://www.krugerpark.co.za/feed/", name: "Kruger Park" },
    { url: "https://www.audubon.org/rss", name: "Audubon Society" },
    { url: "https://www.oceana.org/feed/", name: "Oceana" },
    { url: "https://www.smithsonianmag.com/rss/animals/", name: "Smithsonian" },
    { url: "https://www.sciencedaily.com/rss/plants_animals.xml", name: "Science Daily" },
    { url: "https://phys.org/rss-feed/biology-news/plants-animals/", name: "Phys.org" },
    { url: "https://www.nature.com/subjects/animals.rss", name: "Nature Journal" },
    { url: "https://www.sciencenews.org/topic/animals/feed", name: "Science News" },
    { url: "https://www.livescience.com/feeds/animals", name: "Live Science" },
    { url: "https://news.mongabay.com/feed/", name: "Mongabay" },
    { url: "https://africafreak.com/feed", name: "Africa Freak" },
    { url: "https://latestsightings.com/feed/", name: "Latest Sightings" },
    { url: "https://a-z-animals.com/feed/", name: "A-Z Animals" },
    { url: "https://www.activewild.com/feed/", name: "Active Wild" },
    { url: "https://www.animalwised.com/feed/", name: "AnimalWised" },
    { url: "https://facts.net/category/nature/animals/feed/", name: "Facts.net" },
    { url: "https://www.worldatlas.com/animals/feed", name: "World Atlas" },
    { url: "https://www.onekindplanet.org/feed/", name: "One Kind Planet" },
    { url: "https://www.theanimalfacts.com/feed/", name: "The Animal Facts" },
    { url: "https://rainforest-alliance.org/feed/", name: "Rainforest Alliance" },
    { url: "https://www.janegoodall.org/feed/", name: "Jane Goodall Institute" },
    { url: "https://blog.wcs.org/feed/", name: "Wildlife Conservation Society" },
    { url: "https://www.fws.gov/news/rss.xml", name: "US Fish & Wildlife" },
    { url: "https://www.nps.gov/feeds/news.rss", name: "National Park Service" },
    { url: "https://www.biologicaldiversity.org/news/feed/", name: "Biological Diversity" },
    { url: "https://www.conservationinstitute.org/feed/", name: "Conservation Institute" },
    { url: "https://wildambience.com/feed/", name: "Wild Ambience" },
    { url: "https://www.treehugger.com/animals-wildlife-4127792/feed", name: "TreeHugger" },
    { url: "https://www.cornelllab.org/feed/", name: "Cornell Lab" },
    { url: "https://blog.nationalgeographic.org/feed/", name: "NatGeo Blog" },
    { url: "https://www.earthtouchnews.com/feed/", name: "Earth Touch News" },
    { url: "https://www.wildlifeonline.me.uk/feed/", name: "Wildlife Online" },
    { url: "https://www.africanconservation.org/feed", name: "African Conservation" },
    { url: "https://safarisafricana.com/feed/", name: "Safaris Africana" },
    { url: "https://www.animalspot.net/feed/", name: "Animal Spot" },
    { url: "https://www.bioexpedition.com/feed/", name: "Bio Expedition" },
    { url: "https://animaldiversity.org/feed/", name: "Animal Diversity" },
    { url: "https://blog.wildlife.state.nh.us/feed/", name: "NH Wildlife" },
    { url: "https://www.outofafricapark.com/feed/", name: "Out of Africa Park" },
    { url: "https://kids.nationalgeographic.com/feed", name: "NatGeo Kids" },
    { url: "https://www.discovery.com/nature/rss", name: "Discovery" },
    { url: "https://www.animalplanet.com/feed", name: "Animal Planet" },
    { url: "https://www.krugerpark.co.za/Kruger_National_Park_Wildlife-travel/kruger-park-wildlife-blog.html/feed", name: "Kruger Wildlife Blog" },
  ],
  REFRESH_INTERVAL: 48 * 60 * 60 * 1000, // 48 hours
};
